config/routes.rb
Rails.application.routes.draw do 
  root to: 'products#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post  '/profileaddresses', to: 'users/registrations#new_profileaddresses'
    post  '/deliveryaddresses',to: 'users/registrations#new_deliveryaddresses'
  end
   
  # マイページ関係
  resources :mypages, only: [:show] do
    member do
      get 'logout'
      get 'card'
    end
  end

  # クレジットカード関係
  resources :creditcards, only: [:new, :create, :destroy]

  # 商品関係
  resources :products do
    member do
      get :check
      get  :buy
      post :buy
    end
    # ↓newのカテゴリー選択部分(Ajaxで動くアクションのルートを作成)
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  # カテゴリー関係
  resources :categories, only: [:new]
  
end

app/views/template/_footer.html.haml
%aside.bottom-banner
  .banner-inner
    %h2.banner-inner__title
      だれでもかんたん、人生を変えるフリマアプリ
    %p.banner-inner__text
      今すぐ無料ダウンロード！
    .badge-btn__footer
      =link_to image_tag("Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg",class: "badge-btn__footer__store"),"https://www.apple.com/jp/ios/app-store/",class:"badge-btn__footer__link"
      =link_to image_tag("google-play-badge.png",class: "badge-btn__footer__play"),"https://play.google.com/store",class:"badge-btn__footer__link"
%footer.all-footer
  %ul.all-footer__contents
    %li.footer-content
      %h2.footer-head
        FURIMAについて
      %ul.footer-list
        %li.footer-list__button
          =link_to "会社概要（運営会社）","#",class: "footer-list__button__link"
        %li.footer-list__button
          =link_to "プライバシーポリシー","#",class: "footer-list__button__link"
        %li.footer-list__button
          =link_to "FURIMA利用規約","#",class: "footer-list__button__link"
    %li.footer-content
      %h2.footer-head
        FURIMAを見る
      %ul.footer-list
        %li.footer-list__button
          =link_to "カテゴリー一覧","#",class: "footer-list__button__link"
        %li.footer-list__button
          =link_to "ブランド一覧","#",class: "footer-list__button__link"
    %li.footer-content
      %h2.footer-head
        ヘルプ＆ガイド
      %ul.footer-list
        %li.footer-list__button
          =link_to "FURIMAガイド","#",class: "footer-list__button__link"
        %li.footer-list__button
          =link_to "FURIMAロゴ利用ガイドライン","#",class: "footer-list__button__link"
        %li.footer-list__button
          =link_to "お知らせ","#",class: "footer-list__button__link"
  .all-footer__logo
    =link_to image_tag("logo/logo-white.png",class: "footer-logo__image"),"#",class: "footer-logo" 
  %p.copyright
    © FURIMA
- if user_signed_in?
  .sell-button
    = link_to new_product_path,class: "product-button" do
      %span.sell-button__text
        出品する
      = image_tag("icon/icon_camera.png",class: "sell-button__image")

app/views/template/_header.html.haml
%header.all-header
  .all-header__inner
    .all-header__inner__main
      %h1.header-logo
        =link_to image_tag("logo/logo.png",class: "header-logo__icon"), root_path, class: "header-logo__link" 
      .header-search
        %form.header-search__form
          %input{type:"serach",placeholder:"キーワードから探す",class:"header-search__form__input"}
          %button{type:"submit",class:"header-search__form__submit"}
            =image_tag("icon/icon-search 1.png",class: "header-search__form__submit__icon") 

    .all-header__inner__nav
      %ul.list-left
        %li.list-left__choice
          カテゴリー
          .list-left__choice__list
            %ul.list-left__choice__list--left
              %li.category-list
                =link_to "すべて","#",class: "category-list__link"  # カテコりー関係なくすべての商品を呼び出す
            %ul.list-left__choice__list--left
              %li.category-list
                - @parents.each do |parent|     # 親の表示
                  =link_to "#{parent.name}","#",class: "parent_category", id: "#{parent.id}"
                  -# 子、孫の追加はJSにて実装
                  %ul.list-left__choice__list--middle
                    %li.children-list     
                      %ul.list-left__choice__list--right
                        %li.grand_children-list
                           
        %li.list-left__choice--brand
          ブランド
          .list-left__choice__list
            %ul.list-left__choice__list--left
              %li.category-list
                =link_to "シャネル","#",class: "category-list__link"
              %li.category-list
                =link_to "グッチ","#",class: "category-list__link"
                
      - if user_signed_in?
        %ul.list-right
          %li.list-right__li
            = link_to "マイページ", mypage_path(current_user.id), class: "list-right__li__link"
          %li.list-right__li
            = link_to "ログアウト", destroy_user_session_path, method: :delete,class: "list-right__li__link"
      - else
        %ul.list-right
          %li.list-right__li
            = link_to "ログイン", new_user_session_path, class: "list-right__li__link"
          %li.list-right__li
            = link_to "新規会員登録", new_user_registration_path, class: "list-right__li__link"

app/views/template/_input-bottom.html.haml
.input-bottom
  %ul.linput-bottom__nav
    %li.nav プライバシーポリシー
    %li.nav フリマ利用規約
    %li.nav 特定商引取に関する表記
  .input-bottom__icon
    = image_tag('logo/logo-white.png', class:'logo-white')
    %p ©️team＿D70

app/views/template/_input-top.html.haml
.input-top
  .input-header
    -# ここのアイコンに後にトップページ移動のリンク編集してください。
    = link_to root_path do
      = image_tag('logo/logo.png', class:'logo')

app/views/template/_product_lists.html.haml
%ul.product__lists
  - products.each do |product|
    %li.product__lists__list
      = link_to product_path(product), class: "list-link" do
        - product.pictures.each_with_index do |picture, index|
          - if index == 0
            = image_tag(picture.image.url, class: "list-image")
        .list-details
          %h3.list-details__name
            = product.name
          .list-details__body
            %ul
              %li
                = product.price
                円
              %li.list-details__body__icon
                = icon("fa","star")
                0
            %p
              （税込）