config/routes.rb
Rails.application.routes.draw do 
  root to: 'products#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post  '/profileaddresses', to: 'users/registrations#new_profileaddresses'
    post  '/deliveryaddresses',to: 'users/registrations#new_deliveryaddresses'
  end
   
  # マイページ関係
  resources :mypages, only: [:show] do
    member do
      get 'logout'
      get 'card'
    end
  end

  # クレジットカード関係
  resources :creditcards, only: [:new, :create, :destroy]

  # 商品関係
  resources :products do
    member do
      get :check
      get  :buy
      post :buy
    end
    # ↓newのカテゴリー選択部分(Ajaxで動くアクションのルートを作成)
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  # カテゴリー関係
  resources :categories, only: [:new]
  
end

app/views/shared/_card_menu.html.haml
.main_card
  %section.card_display
    %h2.card_display__header
      支払い方法
    .card_display__body
      - if @creditcard.present?
        .credit_card__list__frame
          .credit_card_info
            .credit_card_info__brand
            .credit_card_info__numbers
              .number
                = "**** **** **** " + @card.last4
              .expiration_date
                .expiration_date__title
                  有効期限
                .expiration_date__info
                  = @exp_month + " / " + @exp_year
          .destroy__function
            .destroy__function__link
              = link_to creditcard_path(@creditcard.id), method: :delete, class: "link__btn--blue" do 
                削除する
      - else
        .card_display__body__inner
          = icon('fas', 'credit-card')
          = link_to "クレジットカードを追加する",new_creditcard_path, class: 'card_display__body__inner__btn'
      

app/views/shared/_logout_menu.html.haml
.main_logout
  .logout__display
    = link_to "ログアウト", "#",class: 'logout__display__btn'
    -# = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'logout__display__btn'
    -# マージ後にdevise導入後上記の記述にする予定です。

app/views/shared/_mypage_contents.html.haml
.main_contents
  %section.mypage_user_icon
    = link_to "#", class: "mypage_user_icon__link" do
      %figure.mypage_user_icon__link__figure
        = image_tag 'material/icon/member_photo_noimage_thumb.png', alt: 'sample', class: 'mypage_user_icon__link__figure__image'
      %h2.user_name
        hoge
      .user_info
        .user_info__evaluation
          評価
          %span.user_info__evaluation--number
            0
        .user_info__exhibits
          出品数
          %span.user_info__exhibits--number
            0
  %section.news
    %h3.news__tab
      <お知らせ>
    .news__content
      %ul.lists
        %li.item
          = link_to "#", class: "item__link" do
            %figure.item__link__figure
              = image_tag 'material/logo/logo.png', alt: 'sample', class: 'item__link__figure__image'
            .item__link__info
              .item__link__info__text
                現在お知らせはございません。
              %time.item__link__info__time
                = icon('fas', 'clock')
                %span.item__link__info__time--num
                  ???時間前
            = icon('fas', 'chevron-right')

  %section.todo
    %h3.todo__tab
      <やることリスト>
    .todo__content
      %ul.lists
        %li.item
          = link_to "#", class: "item__link" do
            %figure.item__link__figure
              = image_tag 'material/logo/logo.png', alt: 'sample', class: 'item__link__figure__image'
            .item__link__info
              .item__link__info__text
                現在やることリストはございません。
              %time.item__link__info__time
                = icon('fas', 'clock')
                %span.item__link__info__time--num
                  ???時間前
            = icon('fas', 'chevron-right')

  %section.parchased_products
    %h3.parchased_products__tab
      <購入した商品>
    .during_trade
      %h3.during_trade__tab
        取引中
      .during_trade__content
        %ul.lists
          %li.item
            = link_to "#", class: "item__link" do
              %figure.item__link__figure
                = image_tag 'material/logo/logo.png', alt: 'sample', class: 'item__link__figure__image'
              .item__link__info
                .item__link__info__text
                  現在取引中の商品はございません。
                .item__link__info__status
                  取引無し
              = icon('fas', 'chevron-right')

    .past_trade
      %h3.past_trade__tab
        過去の取引
      .past_trade__content
        %ul.lists
          %li.item
            = link_to "#", class: "item__link" do
              %figure.item__link__figure
                = image_tag 'material/logo/logo.png', alt: 'sample', class: 'item__link__figure__image'
              .item__link__info
                .item__link__info__text
                  現在過去に取引した商品はございません。
                .item__link__info__status
                  取引無し
              = icon('fas', 'chevron-right')

app/views/shared/_mypage_menu.html.haml
.main_menu
  %nav.menu__nav
    %ul.menu__nav__list
      %li.menu__nav__list__item
        = link_to mypage_path(current_user.id), class: "menu__nav__list__item__link" do
          マイページ
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          お知らせ
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          やることリスト
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          いいね一覧
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          出品する
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          出品した商品ー出品中
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          出品した商品ー取引中
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          出品した商品ー売却済み
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          購入した商品ー取引中
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          購入した商品ー過去の取引
          = icon('fas', 'chevron-right')
    %h3.menu__nav__head
      設定
    %ul.menu__nav__list
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          プロフィール
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          発送元・お届け先住所変更
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to card_mypage_path(current_user.id), class: "menu__nav__list__item__link" do
          支払い方法
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          メール/パスワード
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          本人情報
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to "#", class: "menu__nav__list__item__link" do
          電話番号の確認
          = icon('fas', 'chevron-right')
      %li.menu__nav__list__item
        = link_to logout_mypage_path(current_user.id), class: "menu__nav__list__item__link" do
          ログアウト
          = icon('fas', 'chevron-right')

app/views/shared/_new_card.html.haml
.main_new_card
  .new_card__registration
    .flash_message_creditcard
      = flash[:add_creditcard]
    %h2.registration__header
      クレジットカード情報入力
    = form_with model: @creditcard, id: "card_form", class: "registration-form" do |f|
      .form_contents
        .form_contents__card_number
          %label.card_no
            カード番号
          %span.form_require
            必須
          = f.text_field :number, class: "form_contents__card_number__input", placeholder: "半角数字のみ", maxlength: "16"

        .form_contents__card_expiration_date
          %label.expiration_date
            有効期限
          %span.form_require
            必須
          %br
          .select_display_month
            = f.select :exp_month,  [["1月", 1], ["2月", 2], ["3月", 3], ["4月", 4], ["5月", 5], ["6月", 6], ["7月", 7], ["8月", 8], ["9月", 9], ["10月", 10], ["11月", 11], ["12月", 12]], {}, {class: "select_month"}
            %span.text-month
              月
          .select_display_year
            = f.select :exp_year,  [["20年", 2020], ["21年", 2021], ["22年", 2022], ["23年", 2023], ["24年", 2024], ["25年", 2025], ["26年", 2026], ["27年", 2027], ["28年", 2028], ["29年", 2029], ["30年", 2030], ["31年", 2031]], {}, {class: "select_year"}
            %span.text-year
              年
        .form_contents__card_security_code
          %label.security_code
            セキュリティーコード
          %span.form_require
            必須
          = f.text_field :cvc, class: "form_contents__security_code__input", maxlength: "4", placeholder: "カード背面４桁もしくは３桁の番号"

        = f.submit "追加する", id: "regist_card", class: "form_contents__submit"
        #card_token