config/routes.rb
Rails.application.routes.draw do 
  root to: 'products#index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
  }
  devise_scope :user do
    post  '/profileaddresses', to: 'users/registrations#new_profileaddresses'
    post  '/deliveryaddresses',to: 'users/registrations#new_deliveryaddresses'
  end
   
  # マイページ関係
  resources :mypages, only: [:show] do
    member do
      get 'logout'
      get 'card'
    end
  end

  # クレジットカード関係
  resources :creditcards, only: [:new, :create, :destroy]

  # 商品関係
  resources :products do
    member do
      get :check
      get  :buy
      post :buy
    end
    # ↓newのカテゴリー選択部分(Ajaxで動くアクションのルートを作成)
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
  end

  # カテゴリー関係
  resources :categories, only: [:new]
  
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category
  has_many :images, dependent: :destroy
  belongs_to_active_hash :product_status
  belongs_to_active_hash :shipping_origin
  belongs_to_active_hash :delivery_cost
  belongs_to_active_hash :delivery_day
  belongs_to :user
  accepts_nested_attributes_for :images, allow_destroy: true

  validates :images, presence: true
  validates :name, presence: true, length: { maximum: 40 }
  validates :explanation, presence: true, length: { maximum: 1000 }
  validates :category_id, :product_status_id, :delivery_cost_id, :shipping_origin_id, :delivery_day_id, presence: true
  validates :price, presence: true, inclusion: 300..9999999

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, except: [:index, :new, :create, :get_category_children, :get_category_grandchildren]
  before_action :set_category, only:  [:index, :new, :show, :edit]
  before_action :call_category, only: [:create, :new, :update, :edit]

  MAX_DISPLAY_NEW_GOODS = 3
  PER_DISPLAY_GOODS = 3

  def index
    @new_goods = Product.all.includes(:images).limit(MAX_DISPLAY_NEW_GOODS).order('created_at DESC').where(buyer: nil)
    @goods = Product.order("RAND()").all.includes(:images).where(buyer: nil).page(params[:page]).per(PER_DISPLAY_GOODS)
  end

  def new
    @product = Product.new
    @product.images.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to root_path
    else
      flash.now[:edit_product] = "必須項目に誤りがあります。もう一度ご確認の上、お試しください。"
      @createError = flash[:edit_product]
      render :new
    end
  end

  def show
    @image = Image.find_by(product_id: params[:id])
    # アクティブハッシュからデータ呼び出し
    @product_status = ProductStatus.find(@product.product_status_id)
    @delivery_cost = DeliveryCost.find(@product.delivery_cost_id)
    @shipping_origin = ShippingOrigin.find(@product.shipping_origin_id)
    @delivery_day = DeliveryDay.find(@product.delivery_day_id)
  end

  # 親カテゴリーが選択された後に動くアクション
  def get_category_children
    #選択された親カテゴリーに紐付く子カテゴリーの配列を取得
    @category_children = Category.find_by(name: "#{params[:parent_name]}", ancestry: nil).children
  end

  # 子カテゴリーが選択された後に動くアクション
  def get_category_grandchildren
    #選択された子カテゴリーに紐付く孫カテゴリーの配列を取得
    @category_grandchildren = Category.find("#{params[:child_id]}").children
  end

  def edit
    @grandchild_category = @product.category
    @child_category = @grandchild_category.parent

    # 編集ページで子カテゴリーを表示する記載
    @category_children_array = ["---"]
    Category.where(ancestry: @child_category.ancestry).each do |children|
      name = children.name
      id = children.id
      @category_children_array << [name, id]
    end

    # 編集ページで孫カテゴリーを表示する記載
    @category_grandchildren_array = ["---"]
    Category.where(ancestry: @grandchild_category.ancestry).each do |grandchildren|
      name = grandchildren.name
      id = grandchildren.id
      @category_grandchildren_array << [name, id]
    end
  end

  def update
    if @product.update(product_params)
      redirect_to root_path
    else
      flash[:edit_product] = "必須項目に誤りがあります。もう一度ご確認の上、お試しください。"
      redirect_to edit_product_path(@product)
    end
  end

  def destroy
    if @product.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  def check
    @image = Image.find_by(product_id: params[:id])
    @user = User.find(current_user.id)
    @creditcard = Creditcard.find_by(user_id: current_user.id)
    if @creditcard.present?
      Payjp.api_key = Rails.application.credentials.test_secret_key
      customer = Payjp::Customer.retrieve(@creditcard.customer_id)
      @card = customer.cards.retrieve(@creditcard.card_id)
      @exp_month = @card.exp_month.to_s
      @exp_year = @card.exp_year.to_s.slice(2,3)
    end
  end

  def buy
    if @product.buyer.present?
      flash[:add_creditcard] = "申し訳ございません。先に他のお客様が購入されました。"      
      redirect_to product_path(@product.id)
    else
      @product.with_lock do
        if current_user.creditcard.present?
          @creditcard = Creditcard.find_by(user_id: current_user.id)
          Payjp.api_key = Rails.application.credentials.test_secret_key
          Payjp::Charge.create(
            amount: @product.price,
            customer: @creditcard.customer_id,
            currency: 'jpy'
          )
          @product.update(buyer: current_user.id)
          redirect_to root_path
        else
          flash[:add_creditcard] = "クレジットカードの登録をお願いします。"
          redirect_to new_creditcard_path
        end
      end
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :explanation, :category_id, :brand, :product_status_id, :delivery_cost_id, :shipping_origin_id, :delivery_day_id, :price, images_attributes: [:image, :_destroy, :id]).merge(user_id: current_user.id)
  end

  # 商品情報
  def set_product
    @product = Product.find(params[:id])
  end

  def set_category
    @parents = Category.where(ancestry: nil).order("id ASC")
  end

  def call_category
    @category_parent_array = ["---"]
     #データベースから、親カテゴリーのみ抽出し、配列化
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent.name
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
.product
  .product__top
    = render partial: '/template/input-top'
  .showing
    .flash_message_edit_product
      = flash[:edit_product]
    = form_with(model: @product, local: true) do |f|
      -# ↓画像投稿部分
      .showing__images
        %label.sub_title
          出品画像 
        %span.required
          必須
        %p.sentence
          最大10枚までアップロードできます
          - if @product.errors.include?(:"images.image")
            %p{style: "color: red;"}
              = @product.errors.full_messages_for(:"images.image").first
        .showing__images__file
          .previews
            - if @product.persisted?
              - @product.images.each_with_index do |image, i|
                .previews__image
                  .previews__image__box
                    = image_tag image.image.url, data: {image: {index: i }}, width: "100", height: '100'
                  .previews__image__btn{data: {btn: {index: i}}}
                    削除する
          %label.input_box
            = f.fields_for :images do |image|
              .input_box__upload{data: {index: "#{image.index}"}}
                = image.file_field :image, class: "input_box__upload__field"
                = icon('fas','camera fa-2x')
              .input_box__check_box
                = image.check_box :_destroy, data:{index: image.index}, value: image.index, class: 'hidden-destroy'
        -# ↑画像投稿部分
        -# ↓商品名&説明部分
        .showing__info
          .showing__info__name
            = f.label :name do
              商品名 
            %span.required
              必須
            .form
              = f.text_field :name, {class: "form__input", placeholder: "40文字まで"}
              - if @product.errors.include?(:name)
                %p{style: "color: red;"}
                  = @product.errors.full_messages_for(:name).first
          .showing__info__explain
            = f.label :explanation do
              商品の説明 
            %span.required
              必須
            .form
              =f.text_area :explanation, {class: "form__input--textarea", placeholder: "商品の説明（色、素材、重さ、定価、注意点など）"}
              - if @product.errors.include?(:explanation)
                %p{style: "color: red;"}
                  = @product.errors.full_messages_for(:explanation).first
        -# ↑商品名&説明部分
        -# ↓商品の詳細部分
        .showing__detail
          %p.sentence
            商品の詳細
          .showing_form-box
            .showing-product-detail__category
              = f.label 'カテゴリー', class: 'showing-default__label'
              %span.required 必須
              - if @product.category_id.nil? || @createError.nil? == false
                .showing-select-wrapper
                  .showing-select-wrapper__box
                    = f.select :category, @category_parent_array, {}, {class: 'form__input', id: 'parent_category'}
                    - if @product.errors.include?(:category)
                      %p{style: "color: red;"}
                        = @product.errors.full_messages_for(:category).first
              - else
                .showing-select-wrapper
                  .showing-select-wrapper__box
                    = f.select :category, @category_parent_array, {selected:@product.category.parent.parent.name}, {class: 'form__input', id: 'parent_category'}
                    - if @product.errors.include?(:category)
                      %p{style: "color: red;"}
                        = @product.errors.full_messages_for(:category).first
                .showing-select-wrapper__added#children_wrapper
                  .showing-select-wrapper__box
                    = f.select :child_category, @category_children_array, {selected:@product.category.parent.id}, {class: 'form__input', id: 'child_category'}
                .showing-select-wrapper__added#grandchildren_wrapper
                  .showing-select-wrapper__box
                    = f.select :category_id, @category_grandchildren_array, {selected:@product.category.id}, {class: 'form__input', id: 'grandchild_category'}
          .showing__detail__brand
            %label.sub_title
              ブランド
            %span.option
              任意
            .form
              = f.text_field :brand, {class: "form__input", placeholder: "例）シャネル"}
          .showing__detail__status
            = f.label :product_status  do
              商品の状態
            %span.required
              必須
            .form
              = f.collection_select :product_status_id, ProductStatus.all, :id, :value, { prompt: '--' }, class: 'form__input'
              - if @product.errors.include?(:product_status_id)
                %p{style: "color: red;"}
                  = @product.errors.full_messages_for(:product_status_id).first
        -# ↑商品の詳細部分
        -# ↓配送について部分
        .showing__delivery
          %p.sentence
            配送について
          .showing__delivery__cost
            = f.label :delivery_cost_id do
              配送料の負担
            %span.required
              必須
            .form
            = f.collection_select :delivery_cost_id, DeliveryCost.all, :id, :value, { prompt: '--' }, class: 'form__input'
            - if @product.errors.include?(:delivery_cost_id)
              %p{style: "color: red;"}
                = @product.errors.full_messages_for(:delivery_cost_id).first
          .showing__delivery__area
            = f.label :shipping_origin_id do
              発送元の地域
              %span.required 必須
            .form
            = f.collection_select :shipping_origin_id, ShippingOrigin.all, :id, :name, { prompt: '--' }, class: 'form__input'
            - if @product.errors.include?(:shipping_origin_id)
              %p{style: "color: red;"}
                = @product.errors.full_messages_for(:shipping_origin_id).first
          .showing__delivery__day
            = f.label :delivery_day_id do
              発送までの日数
            %span.required
              必須
            .form
            = f.collection_select :delivery_day_id, DeliveryDay.all, :id, :value, { prompt: '--' }, class: 'form__input'
            - if @product.errors.include?(:delivery_day_id)
              %p{style: "color: red;"}
                = @product.errors.full_messages_for(:delivery_day_id).first
        -# ↑配送について部分
        -# ↓価格部分
        .showing__price
          %p.sentence
            価格（¥300〜9,999,999）
          .showing__price__box
            .showing__price__box__left
              = f.label :price do
                販売価格
              %span.required
                必須
            .showing__price__box__right
              ¥
              = f.text_field :price, {class: 'form__price',id: 'form__price-input', placeholder: '例）300'}
              - if @product.errors.include?(:price)
                %p{style: "color: red;"}
                  = @product.errors.full_messages_for(:price).first
              -# ↑販売価格入力部分です
              -# ↓販売手数料・販売利益を表示部分です
          .showing__price__smallbox
            .showing__price__smallbox__left
              %p.sentence--cost
                販売手数料 （10%）
            .showing__price__smallbox__right{ id: 'form__fee' }
              ー
          .showing__price__smallbox
            .showing__price__smallbox__left
              %p.sentence--cost
                販売利益
            .showing__price__smallbox__right{ id: 'form__profit' }
              ー
              -# ↑販売手数料・販売利益を表示部分です。
        -# ↑価格部分
        -# ↓アクション部分
        .showing__action
          .showing__action__btns
            .showing__action__btns--submit
              = f.submit "出品する", {class:"link__btn--white"}
            .showing__action__btns--buttom
              = link_to "#", class: "link__btn--black" do
                下書きに保存する
            .showing__action__btns--back
              = link_to root_path, class: "link__btn--blue" do
                トップページへもどる
          %p.showing__action__note
            禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
        -# ↑アクション部分
  .product__end
    = render partial: '/template/input-bottom'

app/views/products/_goods_lists.html.haml
%ul.goods__lists
  - goods.each do |g|
    %li.goods__lists__list
      = link_to product_path(g), class: "list-link" do
        - g.images.each_with_index do |image, index|
          - if index == 0
            = image_tag(image.image.url, class: "list-image")
        .list-details
          %h3.list-details__name
            = g.name
          .list-details__body
            %ul
              %li
                = g.price
                円
              %li.list-details__body__icon
                = icon("fa","star")
                0
            %p
              （税込）

app/views/products/_product_lists.html.haml
%ul.product__lists
  - products.each do |product|
    %li.product__lists__list
      = link_to product_path(product), class: "list-link" do
        - product.images.each_with_index do |image, index|
          - if index == 0
            = image_tag(image.image.url, class: "list-image")
        .list-details
          %h3.list-details__name
            = product.name
          .list-details__body
            %ul
              %li
                = product.price
                円
              %li.list-details__body__icon
                = icon("fa","star")
                0
            %p
              （税込）

app/views/products/check.html.haml
.input-top
  = render partial: '/template/input-top'

  .products-buy_contents
    .products-buy_content
      .products-buy_content__title
        購入内容の確認
      .products-buy_content__image
        .products-buy_boxs
          .products-buy_boxs__item
            .buy-image
              = image_tag @image.image.to_s
            .buy-image_info
              %p.buy-title
                = @product.name
              %span.buy-price
                = "¥ #{@product.price}"
              %span.buy-price-info（税込）送料込み
              
      .products-buy_item
        .products-buy_item__form
          .buy-item
            %ul.buy-price
              %li.buy-price__title 支払い金額
              %li.buy-price__pay
                = "¥ #{@product.price}"

          .buy-user__info
            %p.buy-nav 支払い方法
            - if @creditcard.present?
              .number
                = "**** **** **** " + @card.last4
              .expiration_date
                .expiration_date__title
                  有効期限
                .expiration_date__info
                  = @exp_month + " / " + @exp_year
            - else
              =link_to new_creditcard_path, class: "buy-info" do
                クレジットカード登録をお願いします

          .buy-user__info
            %p.buy-nav 配送先
            = "お届け先氏名：#{@user.deliveryaddress.family_name} #{@user.deliveryaddress.given_name}"
            %br
            = "お届け先住所：#{@user.deliveryaddress.prefectures} #{@user.deliveryaddress.city}"
            
          .buy-submit
            %p
              郵便局/コンビニ受取をご希望の方は、購入後に取引画面
              から受取場所を変更をすることが可能です。出品者が発送作業を
              開始した後は受取場所の変更ができませんので、早めに変更を行ってください。

            =link_to buy_product_path, class:"item-buy-btn" do
              購入する

  .products-bottom
    = render partial: '/template/input-bottom'

app/views/products/edit.html.haml
=render "form"

app/views/products/index.html.haml
.top-page
  = render "/template/header"
  %section.top-page__title
    .title-contents
      %h2.title-contents__font
        %br/
        人生を変えるフリマアプリ
      %p.title-contents__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .badge-btn
        =link_to image_tag("Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg",class: "badge-btn__store"),"https://www.apple.com/jp/ios/app-store/",class:"badge-btn__link"
        =link_to image_tag("google-play-badge.png",class: "badge-btn__play"),"https://play.google.com/store",class:"badge-btn__link"
  %section.top-page__reason
    %h2.toppage-subtitle
      FURIMAが選ばれる3つの理由
    %ul.reason-lists
      %li.reason-lists__list
        .reason-lists__list__pict
          %span.pict-number
            1
          =image_tag("pict/pict-reason-01.jpg",class: "pict-image")
        %h3.reason-lists__list__text
          %span
            3分
          ですぐに出品
        %p.reason-lists__list__description
          スマホで入力するだけで簡単に出品できる！
      %li.reason-lists__list
        .reason-lists__list__pict
          %span.pict-number
            2
          =image_tag("pict/pict-reason-02.jpg",class: "pict-image")
        %h3.reason-lists__list__text
          %span
            シンプル
          で使いやすい
        %p.reason-lists__list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.reason-lists__list
        .reason-lists__list__pict
          %span.pict-number
            3
          =image_tag("pict/pict-reason-03.jpg",class: "pict-image")
        %h3.reason-lists__list__text
          手数料
          %span
            業界最安
        %p.reason-lists__list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
  %section.top-page__ad
    .top-page__ad__inner
      %h2.ad-title
        会員数日本一位
      %p.ad-text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .badge-btn
        =link_to image_tag("Download_on_the_App_Store_Badge_US-UK_RGB_blk_092917.svg",class: "badge-btn__store"),"https://www.apple.com/jp/ios/app-store/",class:"badge-btn__link"
        =link_to image_tag("google-play-badge.png",class: "badge-btn__play"),"https://play.google.com/store",class:"badge-btn__link"
  %section.top-page__feature
    %h2.toppage-subtitle
      FURIMAの特徴
    %ul.feature-lists
      %li.feature-lists__list
        %figure.feature-lists__list__image
          = image_tag("icon/icon-01.png",class: "feature-image")
        %h3.feature-lists__list__subtitle
          簡単に売り買いできる
        %p.feature-lists__list__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %li.feature-lists__list
        %figure.feature-lists__list__image
          = image_tag("icon/icon-03.png",class: "feature-image")
        %h3.feature-lists__list__subtitle
          売上金は即日振込みに対応
        %p.feature-lists__list__text
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %li.feature-lists__list
        %figure.feature-lists__list__image
          = image_tag("icon/icon-04.png",class: "feature-image")
        %h3.feature-lists__list__subtitle
          様々な支払いに対応
        %p.feature-lists__list__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.top-page__pickup
    %h2.toppage-subtitle__pickup
      ピックアップカテゴリー
    .goods__main
      .goods__head
        = link_to "#",class: "goods__head__link" do
          %h3.goods__head__link__title
            新規投稿商品
      = render partial: "goods_lists", locals: {goods: @new_goods}
  %section.top-page__pickup--brand
    %h2.toppage-subtitle__pickup
      ピックアップブランド
    .goods__main
      .goods__head
        = link_to "#",class: "goods__head__link" do
          %h3.goods__head__link__title
            アーカイバ
      = render partial: "goods_lists", locals: {goods: @goods}
      .goods_paginate
        = paginate @goods
  %aside.top-page__download
.top-page__footer
%a.top-page__sell
= render "/template/footer"

app/views/products/new.html.haml
=render "form"

app/views/products/show.html.haml
.header
  = render partial: '/template/header'
.main
  .show-main
    .content-leftqq
    .content-right
      .top-content
        .flash_message_creditcard
        .item-box
          %h2.item-box__name
            = @product.name
          .item-box__body
            %ul
              %li
                = image_tag @image.image.to_s
                .item-box__body__items
                  %ul
                    %li   
                    - @product.images.each_with_index do |image, i|
                      = image_tag image.image.url, data: {image: {index: i }}
              
          .item-box__price 
            %span= "¥ #{@product.price}"
            .item-box__price__detail
              %span (税込み)
              %span 送料込み

            - if user_signed_in?
              - if @product.user_id == current_user.id && @product.buyer.blank?
                = link_to edit_product_path, class:"item-buy-btn" do
                  編集

                = link_to product_path, method: :delete, class:"item-delete-btn" do
                  削除

              - else
                - if @product.buyer.blank?
                  = link_to check_product_path, class:"item-buy-btn" do
                    購入する
                    
                - else
                  = link_to "#", class:"item-buy-btn" do
                    売約済み
            - else
              = link_to root_path, class:"item-buy-btn" do
                トップページへ
          .item-detail
          =@product.explanation
          .table
            %table
              %tbody
                %tr
                  %th 出品者
                  %td=@product.user.nickname
                %tr
                  %th カテゴリー
                  %td=@product.category.name
                %tr
                  %th ブランド
                  %td=@product.brand
                %tr
                  %th 商品のサイズ
                  %td
                %tr
                  %th 商品の状態
                  %td=@product_status.value
                %tr
                  %th 配送料の負担
                  %td=@delivery_cost.value
                %tr
                  %th 発送元の地域
                  %td=@shipping_origin.name
                %tr
                  %th 発送日の目安
                  %td=@delivery_day.value
          .optional-area
            %ul
              %li.optional-area__left
                %i= icon('fa', 'star')
                いいね 0
            %ul
              %li.optional-area__right
                = link_to "#" do
                  %i= icon('fa', 'flag')
                  不適切な商品の通報
        .comment-box
          %ul.comment-contents
          %form.new-comment
            %textarea.input-text{type: "text"}
          %p.notice-msg
            相手のことを考え丁寧なコメントを心がけましょう。
            %br 不快な言葉遣いなどは利用制限や退会処分となることがあります。
          %button{type: "submit", class: "comment-btn"}
            %i= icon('fa', 'comment')
            コメントする
      %ul.links
        %li
          = link_to "#" do
            %i= icon('fa', 'angle-left')
            %span
            前の商品
      %ul.links-right
        %li
          = link_to "#" do
            %span
            後ろの商品
            %i= icon('fa', 'angle-right')
.footer
  = render partial: '/template/footer'